# Generated by Django 5.2.6 on 2025-09-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='face_encoding',
            new_name='face_embedding',
        ),
    ]
